♻️  Make minor improvements

diff --git a/bin/get-content-encoding b/bin/get-content-encoding
--- a/bin/get-content-encoding
+++ b/bin/get-content-encoding
@@ -40,12 +40,12 @@ declare -r -a CURL_DEFAULT_OPTIONS=(
 
 check_for_sdch() {
 
-    declare availDicts=""
+    declare availDicts=''
     declare currentHeaders="$1"
-    declare dict=""
-    declare dictClientID=""
-    declare dicts=""
-    declare i=""
+    declare dict=''
+    declare dictClientID=''
+    declare dicts=''
+    declare i=''
     declare url="$2"
 
     # Check if the server advertised any dictionaries
@@ -58,7 +58,7 @@ check_for_sdch() {
     if [ -n "$dicts" ]; then
         for i in $dicts; do
 
-            dict=""
+            dict=''
 
             # Check if the dictionary location is specified as a path,
             # and if it is, construct it's URL from the host name of the
@@ -105,11 +105,11 @@ check_for_sdch() {
 
 get_content_encoding() {
 
-    declare currentHeaders=""
-    declare encoding=""
-    declare headers=""
-    declare indent=""
-    declare tmp=""
+    declare currentHeaders=''
+    declare encoding=''
+    declare headers=''
+    declare indent=''
+    declare tmp=''
     declare url="$1"
 
     headers="$(curl "${CURL_DEFAULT_OPTIONS[@]}" \
@@ -168,17 +168,22 @@ get_content_encoding() {
 main() {
 
     # Check if `cURL` is installed
-    if [ ! -x "$(command -v "curl")" ]; then
-        printf "cURL is required, please install it!\n"
-        exit;
+
+    command -v 'curl' &> /dev/null
+
+    if [ $? -ne 0 ]; then
+        printf 'cURL is required, please install it!\n'
+        exit 1
     fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     while [ $# -ne 0 ]; do
         get_content_encoding "$1"
         shift
     done
 
-    printf "\n"
+    printf '\n'
 
 }
 
